--/
/*
CREATE OR REPLACE PROCEDURE PROC_PAFF_DROPSEQ ( V_NAME IN VARCHAR2) AS V_COUNT INT;
BEGIN
	SELECT COUNT(1) INTO V_COUNT FROM USER_SEQUENCES A WHERE SEQUENCE_NAME=UPPER(V_NAME);
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP SEQUENCE' || V_NAME  ||' PURGE';   ;
	END IF;
END PROC_PAFF_DROPSEQ;
/

--/
CREATE OR REPLACE PROCEDURE PROC_PAFF_DROPTABLE ( T_NAME IN VARCHAR2) 
AS
T_COUNT INT;
BEGIN
	SELECT COUNT(1) INTO t_COUNT FROM USER_TABLES A WHERE TABLE_NAME=UPPER(V_NAME);
	IF V_COUNT > 0 THEN
		EXECUTE IMMEDIATE 'DROP TABLE' || T_NAME;
	END IF;
END;
/
*/
DROP TABLE T_PAFF_TEST_USER;
DROP SEQUENCE SEQ_PAFF_TEST_USER;

CREATE SEQUENCE SEQ_PAFF_TEST_USER MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 10 NOORDER  NOCYCLE;
CREATE TABLE T_PAFF_TEST_USER(USER_ID NUMBER(11) NOT NULL,USER_NAME NVARCHAR2(60) NOT NULL,PRIMARY KEY (USER_ID));

INSERT INTO T_PAFF_TEST_USER (USER_ID,USER_NAME) VALUES(SEQ_PAFF_TEST_USER.NEXTVAL,'admin');
INSERT INTO T_PAFF_TEST_USER (USER_ID,USER_NAME) VALUES(SEQ_PAFF_TEST_USER.NEXTVAL,'demo');
INSERT INTO T_PAFF_TEST_USER (USER_ID,USER_NAME) VALUES(SEQ_PAFF_TEST_USER.NEXTVAL,'test');
INSERT INTO T_PAFF_TEST_USER (USER_ID,USER_NAME) VALUES(SEQ_PAFF_TEST_USER.NEXTVAL,'test123');

COMMIT;
/*
DROP PROCEDURE PROC_PAFF_DROPSEQ;
DROP PROCEDURE PROC_PAFF_DROPTABLE;
*/